### ISSUE TITLE
注册登录页面遇到的bug

### ISSUE THREAD

**Issue by Z-Zzz-321** [startscloud/mitao-issue#2]
手机型号：iPhone8 
软件版本：12.4.1

第一次输入手机号，提示验证码发送失败。
第二次输入完验证码后显示验证码错误。

![WechatIMG411](https://user-images.githubusercontent.com/372241/67175655-86791800-f3f9-11e9-859c-fe6bacf75720.jpeg)

**Comment by yiquncode** [comment]
我在安卓和IOS上昨天测试遇到相同的问题
